config/routes.rb
Rails.application.routes.draw do
  devise_for :players

  root to: "offers#index"

  resources :offers, only: [:index]
  resources :claimed_offers, only: [:index, :show, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class

  def show_errors
    errors.full_messages.to_sentence
  end
end

app/models/claimed_offer.rb
class ClaimedOffer < ApplicationRecord
  belongs_to :player
  belongs_to :offer
end

app/models/concerns/has_gender.rb
module HasGender
  extend ActiveSupport::Concern

  included do
    enum gender: { male: 1, female: 2 }

    validates :gender, inclusion: { in: genders }
  end
end

app/models/offer.rb
class Offer < ApplicationRecord
  include HasGender

  has_many :claimed_offers
  has_many :players, through: :claimed_offers, dependent: :destroy

  validates_presence_of :age
end

app/models/player.rb
class Player < ApplicationRecord
  include HasGender

  LEGAL_AGE = 21.freeze

  has_many :claimed_offers
  has_many :offers, through: :claimed_offers, dependent: :destroy

  validates_presence_of :birthday

  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable, :confirmable
  
  def age
    Age.from(birthday)
  end

  def minor?
    age < LEGAL_AGE
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend

  before_action :authenticate_player!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :gender, :birthday])
  end
end

app/controllers/claimed_offers_controller.rb
class ClaimedOffersController < ApplicationController
  before_action :find_offer, only: [:create]

  def index
    @pagy_claimed, @claimed_offers = pagy(current_player.offers)
  end

  def create
    offer_claim = OfferClaim.new(current_player)
    
    if offer_claim.claim(@offer)
      redirect_to offers_path, notice: 'Offer claimed successfully'
    else
      redirect_to offers_path, alert: current_player.show_errors
    end
  end

  private

  def offer_id_param
    params.require(:offer_id)
  end

  def find_offer
    @offer = Offer.find(offer_id_param)
  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  def index
    @pagy_claimed, @claimed_offers = pagy(current_player.offers, page_param: 'page_claimed')
    @pagy_targeted, @targeted_offers = pagy(offer_finder.targeted, page_param: 'page_targeted')
    @pagy_may_interest, @may_interest_offers = pagy(offer_finder.may_interest, page_param: 'page_may_interest')
  end

  private

  def offer_finder
    @_offer_finder ||= OfferFinder.new(current_player)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend

  def gender_options_for_select
    Player.genders.map {|k, _| [k.humanize.capitalize, k] }
  end
end

app/views/claimed_offers/index.html.erb
<div class="flex flex-row justify-center">
  <%= render partial: 'offers/list', locals: { offers: @claimed_offers, title: 'Claimed Offers', pagy: @pagy_claimed, claimed: true } %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Influence Mobile</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if player_signed_in? %>
      <%= render 'shared/navbar' %>
    <% end %>
  
    <%= render 'shared/flash' %>

    <main class="container mx-auto mt-4 px-5">
      <%= yield %>
    </main>
  </body>
</html>

app/views/offers/_list.html.erb
<% claimed ||= false %>

<div class="flex flex-col gap-y-4 bg-blue-50 rounded p-5 max-w-2xl flex-1 min-w-lg">
  <p class="text-xl font-semibold text-center mb-4 border-b-2 pb-2"><%= title %></p>

  <% offers.each do |offer| %>
    <%= render offer, claimed: claimed %>
  <% end %>

  <div class="flex justify-center gap-x-2">
    <%== pagy_nav(pagy) if pagy.pages > 1 %> 
  </div>
</div>

app/views/offers/_offer.html.erb
<div class="flex flex-row justify-between items-center shadow bg-white rounded p-3">
  <div class="flex flex-col gap-y-1">
    <span class="text-sm font-semibold text-brown"># <%= offer.id %></span>
    <span><%= offer.description.humanize %></span>
  </div>

  <% unless claimed %>
    <div>
      <%= button_to 'Claim Offer', claimed_offers_path(offer, params: { offer_id: offer.id }), method: :post, class: 'bg-green-400 p-2 rounded font-semibold text-sm' %>
    </div>
  <% end %>
</div>

app/views/offers/index.html.erb
<div class="flex flex-col md:flex-row md:gap-x-4 gap-y-4">
  <%= render partial: 'offers/list', locals: { offers: @claimed_offers, title: 'Claimed Offers (Debug purpose)', pagy: @pagy_claimed, claimed: true } %>
  <%= render partial: 'offers/list', locals: { offers: @targeted_offers, title: 'Offers for you', pagy: @pagy_targeted } %>
  <%= render partial: 'offers/list', locals: { offers: @may_interest_offers, title: 'May interest you', pagy: @pagy_may_interest } %>
</div>

app/views/shared/_flash.html.erb
<% if flash.any? %>
  <div class="flex justify-center">
    <% flash.each do |type, message| %>
      <div class="shrink bg-gray-100 shadow rounded p-4 font-semibold text-sm"><%= message %></div>
    <% end %>
  </div>
<% end %>

<% flash.clear %>

app/views/shared/_navbar.html.erb
<header class="bg-white border-b-2 flex justify-around py-4 text-sm font-semibold leading-6 mb-4">
  <div class="flex justify-around flex gap-x-6">
    <div><%= link_to 'All Offers', offers_path %></div>
    <div><%= link_to 'Claimed Offers', claimed_offers_path %></div>
  </div>

  <div class="flex gap-x-6">
    <div>Hello, <%= current_player.name %></div>
    <%= button_to destroy_player_session_path, method: :delete, class: "text-red-500" do %>
      Log out &rarr;</span>
    <% end %>
  </div>
</header>